### PR TITLE
Converting CI to GH actions

### PR DESCRIPTION
**Pull request by ryanml**

### CODE REVIEW

**Review by Gudahtt — DISMISSED** [review]
LGTM!

**Comment by Gudahtt** [comment]
I've just enabled GitHub Actions. This needs another push to get those started I think? Then I can update the required status check.

**Comment by ryanml** [comment]
@Gudahtt repushed

**Review by Gudahtt — APPROVED** [review]

**Comment by Gudahtt** [comment]
Branch protection settings updated! I've disabled status updates for this project on CircleCI now as well. Someone will still need to stop builds on CircleCI, but at least it won't annoy us with red X's in the meantime.

**Review by Kinou90100 — COMMENTED** [review]
#58 
#57 
#56 
#55 
#54 
@Christoc90
@Kinou90100

**Comment by Kinou90100** [comment]
#58 
#57 
#56 
#55 
#47 
@Kinou90100 
@Christoc90

**Pull request merged**
